server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://configuration-server:8888/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
