server:
  port: 8081

spring:
  application:
    name: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:53704/realms/sweetify

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/